# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpTYu-jG6XAbeUxYC_CaXbtn52qMnCaT
"""

import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt

# Configuración de la página
st.set_page_config(page_title="Predictor de Calidad del Vino", layout="centered")

# Cargar el modelo pre-entrenado
model = joblib.load('wine_model.pkl')

st.title("🍷 Predictor de Calidad de Vino Tinto")
st.markdown("Ajustá los parámetros físico-químicos para predecir la calidad del vino (escala del 3 al 8) y entender qué factores influyen más.")

# Crear columnas para organizar los sliders
col1, col2 = st.columns(2)

with col1:
    fixed_acidity = st.slider('Acidez Fija', 4.0, 16.0, 8.3)
    volatile_acidity = st.slider('Acidez Volátil', 0.1, 1.6, 0.5)
    citric_acid = st.slider('Ácido Cítrico', 0.0, 1.0, 0.3)
    residual_sugar = st.slider('Azúcar Residual', 0.9, 15.5, 2.5)
    chlorides = st.slider('Cloruros', 0.01, 0.61, 0.08)
    free_sulfur_dioxide = st.slider('Dióxido de Azufre Libre', 1.0, 72.0, 14.0)

with col2:
    total_sulfur_dioxide = st.slider('Dióxido de Azufre Total', 6.0, 289.0, 46.0)
    density = st.slider('Densidad', 0.990, 1.004, 0.997)
    pH = st.slider('pH', 2.7, 4.0, 3.3)
    sulphates = st.slider('Sulfatos', 0.3, 2.0, 0.6)
    alcohol = st.slider('Alcohol (%)', 8.0, 15.0, 10.4)

# Botón de predicción
if st.button('Predecir Calidad e Impacto'):
    # Crear un DataFrame con los inputs del usuario
    features = [
        'fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
        'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
        'pH', 'sulphates', 'alcohol'
    ]

    input_data = pd.DataFrame([[
        fixed_acidity, volatile_acidity, citric_acid, residual_sugar,
        chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density,
        pH, sulphates, alcohol
    ]], columns=features)

    # Realizar la predicción
    prediction = model.predict(input_data)[0]

    st.success(f"🍇 La calidad estimada del vino es: **{prediction}** / 8")

    st.divider()

    # Sección de Explicabilidad (Feature Importance)
    st.subheader("📊 ¿Qué factores definen la calidad en este modelo?")
    st.markdown("El gráfico muestra qué variables tienen más peso en el criterio del modelo (Random Forest) para asignar el puntaje final.")

    # Extraer importancias del modelo
    importances = model.feature_importances_

    # Crear un DataFrame para ordenar los datos del gráfico
    importance_df = pd.DataFrame({'Variable': features, 'Importancia': importances})
    importance_df = importance_df.sort_values(by='Importancia', ascending=True)

    # Crear el gráfico con Matplotlib
    fig, ax = plt.subplots(figsize=(8, 5))

    # Usar un color bordó para mantener la estética vitivinícola
    ax.barh(importance_df['Variable'], importance_df['Importancia'], color='#722F37')

    ax.set_xlabel('Peso en la Decisión')
    ax.set_title('Importancia de las Variables Físico-Químicas')

    # Quitar bordes para que se vea más limpio en la web
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Mostrar el gráfico en Streamlit
    st.pyplot(fig)